
INSERT INTO `badges` (`id`, `titre`, `description`, `emoji`, `thematique_id`, `nbr_min_point`, `created_by`, `last_updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Ami de la nature', '\"Ami de la nature\" peut désigner le mouvement associatif international des Amis de la nature, fondé en 1895, qui promeut les loisirs de plein air et la défense de l\'environnement, ou une personne qui a une forte affinité avec la nature et s\'engage pour sa préservation.', '🌍', 7, 8, 1, 4, 1, '2025-11-05 14:41:35', '2025-11-05 14:45:42', '2025-11-05 14:45:42');

INSERT INTO `badge_users` (`id`, `user_id`, `badge_id`, `created_at`, `updated_at`) VALUES
(1, 2, 1, '2025-10-14 08:53:39', '2025-10-14 08:53:39'),
(2, 2, 2, '2025-10-14 08:53:39', '2025-10-14 08:53:39');

INSERT INTO `evaluations` (`id`, `thematique_id`, `user_id`, `partie_id`, `score`, `temps`, `question`, `drawing_data`, `created_at`, `updated_at`) VALUES
(1, 2, 2, 3, 10, '00:01:42', '[{\"question_id\":3,\"selected_option\":{\"text\":\"Être en retard c\'est lorsque tu viens avant l\'heure\",\"isCorrect\":false,\"mediaUrl\":null,\"contentType\":\"text\",\"mediaDescription\":null},\"correct_option\":{\"text\":\"Être en retard c\'est lorsque tu viens après l\'heure\",\"isCorrect\":true,\"mediaUrl\":null,\"contentType\":\"text\",\"mediaDescription\":null},\"intitule_text\":\"Qu\'est-ce qu\'être en retard ?\",\"intitule_media_url\":null,\"intitule_media_description\":null,\"explication\":null}]', 'drawings/2025/10/drawing_2_3_1760435619.png', '2025-10-14 08:53:39', '2025-10-14 08:53:39');

INSERT INTO `niveaux` (`id`, `numero`, `nom`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 1, 'Niveau de base', 'Niveau 1 de base créé par défaut pour toutes les thématiques.', '2025-10-04 18:46:46', '2025-10-08 08:45:55', NULL),
(2, 2, 'FOWA', 'fffggvgv', '2025-10-08 08:13:28', '2025-10-08 08:14:26', '2025-10-08 08:14:26'),
(3, 2, 'On charbone', 'iyugytf', '2025-10-08 08:21:58', '2025-10-08 09:12:23', '2025-10-08 09:12:23'),
(4, 2, 'FOWA', 'kds,v', '2025-10-08 09:13:48', '2025-10-08 09:14:04', '2025-10-08 09:14:04'),
(5, 2, 'Calvin', 'fsdlkn', '2025-10-08 09:13:57', '2025-10-08 09:18:02', '2025-10-08 09:18:02'),
(6, 2, 'Rober', 'rgb2', '2025-10-08 09:17:54', '2025-10-08 09:18:51', '2025-10-08 09:18:51'),
(7, 2, 'x', 'x', '2025-10-08 09:18:23', '2025-10-08 09:20:51', '2025-10-08 09:20:51'),
(8, 2, 'Jeremy', 'jerrar', '2025-10-08 09:20:35', '2025-10-08 09:22:12', '2025-10-08 09:22:12'),
(9, 2, 'parfum de pacouraban', 'parfum de pacouraban', '2025-10-08 09:22:05', '2025-10-08 09:23:09', '2025-10-08 09:23:09'),
(10, 2, 'Salmonelle', 'flsq', '2025-10-08 09:23:00', '2025-10-08 09:23:50', '2025-10-08 09:23:50'),
(11, 2, 'x', 'x', '2025-10-08 09:23:45', '2025-10-08 09:25:50', '2025-10-08 09:25:50'),
(12, 2, 'y', 'y', '2025-10-08 09:25:44', '2025-10-08 09:28:01', '2025-10-08 09:28:01'),
(13, 2, 'bonbon', 'bonbon', '2025-10-08 09:27:49', '2025-10-08 09:29:24', '2025-10-08 09:29:24'),
(14, 2, 'pomme', 'pomme', '2025-10-08 09:29:19', '2025-10-08 09:31:06', '2025-10-08 09:31:06'),
(15, 2, 'riz', 'riz', '2025-10-08 09:31:00', '2025-10-08 09:31:52', '2025-10-08 09:31:52'),
(16, 2, 'On charbone', 'sdf', '2025-10-08 09:31:48', '2025-10-08 09:33:53', '2025-10-08 09:33:53'),
(17, 2, 'Client user', 'Client user', '2025-10-08 09:33:45', '2025-10-08 09:35:14', '2025-10-08 09:35:14'),
(18, 2, 'x', 'x', '2025-10-08 09:35:07', '2025-10-08 09:35:14', NULL);

INSERT INTO `parties` (`id`, `numero`, `name`, `description`, `thematique_id`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 1, 'Le petit voyage de Koulou la tortue', 'Lorsqu\'on voyage on tient compte du temps et de l\'espace, c\'est-à-dire de l\'heure de départ ou d\'arrivée, de la durée du voyage... notre ami la tortue n\'a pas l\'air de le savoir !', 1, '2025-10-04 18:46:46', '2025-10-04 18:46:46', NULL),
(2, 2, 'La petite tête de mule de Fari l\'âne', 'La têtutesse qualifie une personne qui refuse d\'obéir à une règle/loi pour ne que chercher à obtenir de manière déterminer sa propre liberté. C\'est le cas de notre ami la Fari.', 1, '2025-10-04 18:46:46', '2025-10-04 18:46:46', NULL),
(3, 1, 'Le grand retard de Koulou chez le roi lion', 'Pendant cette séance, il s’agit d’amener les enfants d’abord à comprendre ce qu’est le retard par rapport à la ponctualité. En outre, il s’agit de les amener à faire une démarcation conceptuelle entre ces deux concepts. Le plus simple pour eux serait certainement de faire cette distinction conceptuelle entre être en retard et être ponctuel.', 2, '2025-10-04 19:03:48', '2025-10-04 19:03:48', NULL),
(4, 1, 'Le recyclage', 'Le recyclage', 7, '2025-10-14 09:19:51', '2025-10-14 09:19:51', NULL);

INSERT INTO `profils` (`id`, `code`, `name`, `sexe`, `age`, `profil`, `user_id`, `niveau_id`, `password`, `is_active`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'FVz6EWoe', 'Mballa', 'Féminin', 8, '/storage/profil/LzjesTSImdmjQaGYE9zsHvZ1cbxCu9gPtDXNqHde.png', 1, 1, '', 0, '2025-11-02 16:43:05', '2025-11-05 13:10:20', NULL),
(2, 'wy1JFGCL', 'John', 'Masculin', 5, '/storage/profil/KIwNxpc4fFZS3vtID7CVpvcDn11Fq3eWU3hx4ASZ.jpg', 1, 1, 'eyJpdiI6InZBeGVXUCt0L3lkWVkwRDVIUXJaZHc9PSIsInZhbHVlIjoicHB5UnVqeStoNk9DV05EV1NGK1Q4dz09IiwibWFjIjoiMDA2MTM4ZTVlMWI1YzliNzUzNWNjYjExNzdmOTY0M2E1NWIwMjExZWYzMDA4MmIyMzM5OWFkODBjZTIzN2E5ZSIsInRhZyI6IiJ9', 0, '2025-11-03 05:52:48', '2025-11-05 13:56:29', NULL);

INSERT INTO `questions` (`id`, `intitule_text`, `intitule_media_url`, `intitule_media_description`, `thematique_id`, `partie_id`, `degre_difficulte`, `type_reponse`, `indice`, `explication`, `reponses`, `numero`, `created_by`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Alors mes amies, dans la vidéo que vous venez regarder, quel est le problème de notre petite tortue Koulou par rapport au léopard ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Le problème se trouve dans ce que la petite tortue n\'arrive pas à faire.', 'RAS', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"mediaUrl\\\":null,\\\"text\\\":\\\"Son probl\\\\u00e8me c\'est parce qu\'elle marche lentement\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"mediaUrl\\\":null,\\\"text\\\":\\\"Son probl\\\\u00e8me est qu\'elle est toujours en retard\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"mediaUrl\\\":null,\\\"text\\\":\\\"Son probl\\\\u00e8me est qu\'elle n\'est pas ponctuelle\\\"}]\"', 1, 1, '2025-09-28 08:26:28', '2025-10-04 22:56:43', NULL),
(2, 'Peux-tu poser une question par rapport à la tortue ou à la panthère dans l\'histoire racontée dans la vidéo ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Pour se poser les bonnes questions, il faut se demander si on peut avoir quelques idées correctes aux questions qu\'on choisit de se poser.', NULL, '\"[{\\\"text\\\": \\\"Pourquoi la tortue ne se réveille pas vite ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Pourquoi la maison de la tortue est si loin qu\'elle n\'arrive à vite?\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Qu\'est-ce que fait la tortue pour ne pas arriver à l\'heure ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 2, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(3, 'Qu\'est-ce qu\'être en retard ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Être en retard c\'est lorsque tu viens après l\'heure\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Être en retard c\'est lorsque tu ne respectes pas l\'heure\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Être en retard c\'est lorsque tu viens avant l\'heure\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 3, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(4, 'Qu\'est-ce qu\'être ponctuel ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Être en retard c\'est lorsque tu viens après l\'heure\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Être en retard c\'est lorsque tu respectes l\'heure\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Être en retard c\'est lorsque tu viens avant l\'heure\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 4, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(5, 'A-t-on le droit d\'être en retard ? Et pourquoi ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Non on n\'a pas le droit, parce qu\'arriver en retard comme la tortue, ce n\'est pas être respectueux de l\'autre\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non on n\'a pas le droit, parce que ça veut dire que tu ne le méprises pas\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Oui on a le droit, parce qu\'on peut faire tout ce qu\'on veut\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 5, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(6, 'Mais est-ce qu\'il y a une situation où on a le droit de venir en retard ou de ne pas venir du tout?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Oui monsieur. On peut être malade\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Oui monsieur. On peut aussi avoir un accident\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non monsieur. Pas d\'excuses.\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 6, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(7, 'Finalement a-t-on vraiment le droit d\'être en retard ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Oui. On peut venir en retard sans se soucier des autres\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non. On n\'a pas le droit de venir en retard car c\'est ne pas respecter les autres.\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non. On n\'a pas le droit d\'arriver en retard parce que ceux qui nous invitent, attendent qu\'on arrive à l\'heure.\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 7, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(8, 'Montre dans ton dessin la différence entre quelqu\'un qui est à l\'heure et quelqu\'un qui est en retard?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Utilise ton doigt sur l\'espace tactile en bas\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Fais des coloris\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Et sauvegarde ton dessin pour le montrer à tes amis et à tes parents\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 8, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(9, 'Alors mes amies, dans la vidéo que vous avez regardé, quel peut être encore le problème de notre petite tortue Koulou par rapport au temps ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Le problème se trouve dans ce que la petite tortue n\'arrive pas à faire.', NULL, '\"[{\\\"text\\\": \\\"Son problème est qu\'elle est toujours en retard\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Son problème c\'est parce qu\'elle marche lentement\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Son problème est qu\'elle n\'est gère pas bien son temps pour être ponctuelle\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 9, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(10, 'Peux-tu poser une question par rapport à la tortue ou à la panthère dans l\'histoire racontée dans la vidéo ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Pour se poser les bonnes questions, il faut se demander si on peut avoir quelques idées correctes aux questions qu\'on choisit de se poser.', NULL, '\"[{\\\"text\\\": \\\"Pourquoi la maison de la tortue est si loin qu\'elle n\'arrive à vite?\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Pourquoi la tortue ne se réveille pas vite ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Qu\'est-ce que fait la tortue pour ne pas arriver à l\'heure ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 10, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(11, 'Pour toi, qu\'est-ce que bien gérer son temps ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"C\'est organiser son temps de manière à ne pas être en retard\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est faire tout ce qu\'on veut de notre temps à n\'importe quel moment\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est s\'adapter au temps qu\'il fait de manière à ne pas subir le temps\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 11, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(12, 'Tu sais ce que signifie organiser son temps? Peux-tu me dire avec des exemples ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"C\'est ranger son temps comme on range sa chambre\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est faire les choses vites sans préparation comme un fou\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est partager son temps en plusieurs tranches comme on coupe un gâteau\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 12, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(13, 'Tu peux aussi me dire avec des exemples ce que signifie s\'adapter à son temps ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"C\'est ne pas voir le temps qu\'il fait comme vouloir sortir de la maison dans la pluie sans parapluie\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est faire avec le temps qu\'on nous donne comme pendant la composition\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est se mettre au rythme ou à la vitesse du temps comme un tam-tam\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 13, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(14, 'Et ça veut dire quoi subir le temps ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"C\'est lorsque tu dois attendre longtemps, même si c\'est long comme quand tu es en salle t\'attende à l\'hôpital\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est lorsque le temps continue a passé, même quand tu voudrais qu\'il s\'arrête comme pendant que tu dors durant la nuit\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est quand on est libre de décider à la place du temps comme on décide de manger ou non\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 14, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(15, 'Peux-tu me dire alors ce que tu penses du temps: est-il le même pour tout le monde ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Oui, le temps est le même pour tous parce que 30 min à l\'école égales 30 min à la maison.\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Oui le temps est le même pace que le jour se lève et se couche au même moment partout\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non, les 30 min à l\'école durent plus que les 30 min à la maison, donc le temps n\'est pas la même chose pour tout le monde\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non, le temps n\'est pas le même, car chaque chose à son temps, il y a les temps de saison pluvieuse et les temps de saison sèche\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 15, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(16, 'Alors mon ami, comment faut-il faire vraiment pour bien gérer son temps afin de ne plus venir en retard ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Il faut ranger son temps, c\'est-à-dire régler son réveil pour se lever tôt le matin\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Il faut marcher lentement comme une tortue sur le chemin et s\'arrêter pour jouer\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"C\'est partager son temps en plusieurs activités pour faire chaque chose à son temps et sans traîner\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 16, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(17, 'Qui peut dessiner un ami qui gère bien son temps et n\'arrive jamais en retard à l\'école ?', NULL, NULL, 2, 3, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Utilise ton doigt sur l\'espace tactile en bas\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Fais des coloris\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Et sauvegarde ton dessin pour le montrer à tes amis et à tes parents\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 17, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(18, 'Alors mes amies. dans la vidéo que vous venez regarder, quel est le problème de notre petit Fari l\'âne par rapport au cheval?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Le problème se trouve dans ce que la petit âne refuse de faire ou veut faire absolument.', NULL, '\"[{\\\"text\\\": \\\"Son problème est qu\'il refuse d\'obéir\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Son problème c\'est que son maître lui tape sur les fesses tout le temps\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Son problème est qu\'il veut être libre et faire tout ce qu\'il veut\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 1, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(19, 'Peux-tu poser une question par rapport à l\'âne ou au cheval dans l\'histoire racontée dans la vidéo ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Pour se poser les bonnes questions, il faut se demander si la question choisi nous fait réfléchir, si elle n\'est pas trop facile pour trouver des idées.', NULL, '\"[{\\\"text\\\": \\\"Pourquoi l\'âne est court?\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Comment être obéissant ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Qu\'est-ce qu\'être obéissant ?\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 2, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(20, 'Qu\'est-ce qu\'être obéissant ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Être obéissant, c\'est partager quelque chose\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Etre obéissant, c\'est respecter les règles ou les lois\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Obéir, ça veut dire que tu dois faire ce que tes aînés de disent\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 3, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(21, 'Qu\'est-ce qu\'être désobéissant ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Être désobéissant, c\'est refuser de faire ce que tes aînés de disent\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Être désobéissant, c\'est partager quelque chose\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Etre désobéissant, c\'est ne pas respecter les règles ou les lois\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 4, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(22, 'Toute les règles sont-elles justes ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Non, toutes les lois ne sont pas juste, par exemple dire qu\'on doit: « traverser la route au feu vert » est une mauvaise loi.\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non, toutes les règles ne sont pas bonnes, par exemple dire que : « seuls certains enfants ont le droit de jouer » est une règle injuste.\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Oui, toutes les règles sont bonnes et il faut les obéir\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 5, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(23, 'Si toutes les règles ou lois ne sont pas bonnes, a-t-on le droit de désobéir aux mauvaises règles ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Oui, on doit désobéir une règle qu\'on juge mauvaise car si on l\'obéit on se met en danger\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Oui, on doit désobéir une loi qu\'on juge injuste car si on l\'obéit on peut faire du mal à l\'autre\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Non, la loi c\'est la loi, il faut l\'obéir\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 6, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(24, 'Finalement comment être vraiment obéissant ?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Il faut d\'abord bien juger ce qu\'on nous demande de faire si c\'est juste ou injustes, bien ou mauvais\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Il faut obéir les règles/lois sans réfléchir car ce sont les adultes qui les ont créées\\\", \\\"isCorrect\\\": false, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Il faut d\'abord bien juger ce qu\'on nous demande de faire si c\'est juste ou injustes, bien ou mauvais\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 7, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(25, 'Montre dans ton dessin la différence entre Fari et le cheval?', NULL, NULL, 1, 2, '1', 'multiple', 'Alors les amis! Regarde sur l\'image.', NULL, '\"[{\\\"text\\\": \\\"Utilise ton doigt sur l\'espace tactile en bas\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Fais des coloris\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}, {\\\"text\\\": \\\"Et sauvegarde ton dessin pour le montrer à tes amis et à tes parents\\\", \\\"isCorrect\\\": true, \\\"mediaUrl\\\": null, \\\"contentType\\\": \\\"text\\\", \\\"mediaDescription\\\": null}]\"', 8, 1, '2025-09-28 08:26:28', '2025-09-28 08:26:28', NULL),
(26, NULL, '/storage/questions/APi5CoN6NbViMlHXy4jRFPrNYwPupAtMZENlgZlD.jpg', 'Dans quelle poubelle doit-on jeter une bouteille en plastique ?', 7, 4, '2', 'unique', 'C\'est la couleur du soleil !', 'Les bouteilles en plastique vont dans la poubelle jaune pour être recyclées et transformées en nouveaux objets.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la poubelle normale\\\",\\\"mediaUrl\\\":null},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la poubelle jaune\\\",\\\"mediaUrl\\\":null},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la poubelle verte\\\",\\\"mediaUrl\\\":null},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Par terre\\\",\\\"mediaUrl\\\":null}]\"', 1, NULL, '2025-07-18 08:06:18', '2025-09-13 10:56:38', NULL),
(27, 'Que veut dire \"recycler\" ?', NULL, NULL, 7, 4, '1', 'unique', 'C\'est comme donner une nouvelle vie aux objets !', 'Recycler, c\'est transformer les déchets en nouveaux objets utiles au lieu de les jeter.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Jeter \\\\u00e0 la poubelle\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Casser en morceaux\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Transformer en quelque chose de nouveau\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Mettre dans un sac\\\"}]\"', 2, NULL, '2025-07-18 08:10:09', '2025-09-13 10:56:38', NULL),
(28, 'Où doit-on jeter les épluchures de légumes ?', NULL, NULL, 7, 4, '1', 'unique', 'Elles peuvent nourrir la terre !', 'Elles peuvent nourrir la terre !', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans le compost\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la poubelle jaune\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la rue\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Dans la poubelle bleue\\\"}]\"', 4, NULL, '2025-07-18 08:12:03', '2025-09-13 10:56:38', NULL),
(29, 'Qu\'est-ce qu\'on peut faire avec une bouteille en plastique vide ?', NULL, NULL, 7, 4, '2', 'unique', 'On peut la transformer en quelque chose d\'utile !', 'Au lieu de jeter, on peut réutiliser une bouteille pour en faire un pot à crayons ou un autre objet utile.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"La jeter par terre\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"La casser\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"La manger\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"En faire un pot \\\\u00e0 crayons\\\"}]\"', 3, NULL, '2025-07-18 08:13:45', '2025-09-13 10:56:38', NULL),
(30, 'Quel symbole trouve-t-on sur les objets recyclables ?', NULL, NULL, 7, 4, '2', 'unique', 'Elles forment un cercle et se suivent !', 'Le symbole de recyclage avec trois flèches qui tournent nous montre qu\'un objet peut être recyclé.', '\"[{\\\"contentType\\\":\\\"media\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":\\\"Etoile\\\",\\\"mediaSourceType\\\":\\\"file\\\",\\\"mediaUrl\\\":\\\"\\\\/storage\\\\/questions\\\\/qSvyF0eAsZxm5gXl3SpxazaVJMNvEagCBIfsKcxN.png\\\"},{\\\"contentType\\\":\\\"media\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":\\\"Trois fl\\\\u00e8ches qui tournent\\\",\\\"mediaSourceType\\\":\\\"file\\\",\\\"mediaUrl\\\":\\\"\\\\/storage\\\\/questions\\\\/L02Ku0413H8bIBTjRZqp2h9XF6857jYmLd7lr29b.png\\\"},{\\\"contentType\\\":\\\"media\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":\\\"Rond\\\",\\\"mediaSourceType\\\":\\\"file\\\",\\\"mediaUrl\\\":\\\"\\\\/storage\\\\/questions\\\\/m1MmzGSBgrC3DwOlS9BPYPKCxWd765t7biuyYTzL.png\\\"}]\"', 6, NULL, '2025-07-18 08:19:47', '2025-09-13 10:56:38', NULL),
(31, 'Que peut-on faire avec du papier journal utilisé ?', NULL, NULL, 7, 4, '2', 'unique', 'Il peut redevenir du papier tout neuf !', 'Le vieux papier peut être recyclé pour fabriquer du nouveau papier, des livres ou des cahiers.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Le br\\\\u00fbler\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Le manger\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Le mettre sous l\'oreiller\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Le recycler en nouveau papier\\\"}]\"', 7, NULL, '2025-07-18 08:22:21', '2025-09-13 10:56:38', NULL),
(32, NULL, '/storage/questions/WYsCnpTRnJB10hUNnBwbkUx8HKzVKse90I4bLpFW.png', 'Pourquoi est-ce important de trier ses déchets ?', 7, 4, '2', 'unique', 'C\'est pour prendre soin de notre belle Terre !', 'En triant nos déchets, on aide à recycler et on protège notre planète en réduisant les déchets.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Pour faire joli\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Pour faire du bruit\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Pour prot\\\\u00e9ger la plan\\\\u00e8te\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Pour se fatiguer\\\"}]\"', 5, NULL, '2025-07-18 08:26:33', '2025-09-13 10:56:38', NULL),
(33, 'Combien de fois peut-on recycler une bouteille en verre ?', NULL, NULL, 7, 4, '3', 'unique', 'C\'est comme si elle avait une vie éternelle !', 'Le verre peut être recyclé à l\'infini sans perdre sa qualité, c\'est un super-héros du recyclage !', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"\\\\u00c0 l\'infini (plein de fois)\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"5 fois\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Jamais\\\"}]\"', 8, NULL, '2025-07-18 08:28:10', '2025-09-13 10:56:38', NULL),
(34, 'Que devient une canette en aluminium après recyclage ?', NULL, NULL, 7, 4, '3', 'unique', 'Elle peut redevenir exactement la même chose !', 'Une canette en aluminium peut être fondue et transformée en nouvelle canette, c\'est magique !', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Elle dispara\\\\u00eet\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Une nouvelle canette\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Un g\\\\u00e2teau\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Une fleur\\\"}]\"', 9, NULL, '2025-07-18 08:29:49', '2025-09-13 10:56:38', NULL),
(35, 'Qu\'est-ce qui arrive si on ne recycle pas ?', NULL, NULL, 7, 4, '3', 'unique', 'Imagine ta chambre si tu ne ranges jamais tes jouets !', 'Sans recyclage, les déchets s\'accumulent et polluent notre belle planète, ce qui rend tristes les animaux et les plantes.', '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Il y a trop de d\\\\u00e9chets partout\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"La plan\\\\u00e8te devient plus belle\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Rien ne change\\\"},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Les animaux sont plus heureux\\\"}]\"', 10, NULL, '2025-07-18 08:31:36', '2025-09-13 10:56:38', NULL),
(36, 'Quelle est la capitale du Cameroun?', NULL, NULL, 2, 1, '2', 'unique', NULL, NULL, '\"[{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":true,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Yaound\\\\u00e9\\\",\\\"mediaUrl\\\":null},{\\\"contentType\\\":\\\"text\\\",\\\"isCorrect\\\":false,\\\"mediaDescription\\\":null,\\\"text\\\":\\\"Douala\\\",\\\"mediaUrl\\\":null}]\"', 11, NULL, '2025-07-18 09:39:22', '2025-09-13 10:56:38', NULL);

INSERT INTO `thematiques` (`id`, `name`, `description`, `parent_id`, `media_type`, `media_url`, `media_description`, `nbr_min_point`, `niveau_id`, `emoji`, `couleur`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Le vivre-ensemble', 'Le vivre-ensemble est un concept central qui permet de comprendre différents rapports entre les divers hommes vivant dans la même société. Il s\'agit de leurs rapports au temps, l\'espace, la générosité, la liberté, au travail, et à la politesse.', NULL, 'url', '/storage/thematique/uPuk62Nr0ZbuIZBPhduS6ckQsE3U1VwTpfHkFNDg.mp4', NULL, 10, 1, '🤝', '#fcb69f', '2025-10-04 18:46:46', '2025-10-13 13:00:15', NULL),
(2, 'Le petit voyage de Koulou la tortue', 'Lorsqu’on voyage on tient compte du temps et de l’espace, c’est-à-dire de l’heure de départ ou d’arrivée, de la durée du voyage, de l’accélération de nos mouvements pour la distance à parcourir (si on se déplace rapidement ou lentement) et d’où on va (du lieu) : notre ami la tortue n’a pas l’air de le savoir !', 1, 'file', '/storage/thematique/3HGiuWQpZ4sH3ilS0Tr1oJaoezqng3sv5G9pryLJ.png', 'Le petit voyage de Koulou la tortue', 8, 1, NULL, NULL, '2025-10-04 19:02:19', '2025-10-04 19:02:19', NULL),
(3, 'Le recyclage', 'Le recyclage', NULL, 'text', NULL, NULL, 1, NULL, '🎨', '#ff6600ff', '2025-10-13 10:48:38', '2025-10-13 10:57:14', '2025-10-13 10:57:14'),
(4, 'Le recyclage', 'Le recyclage', NULL, 'text', NULL, NULL, 1, 18, '🎨', '#ff6600ff', '2025-10-13 10:50:15', '2025-10-13 10:57:12', '2025-10-13 10:57:12'),
(5, 'Le recyclage', 'Le recyclage', NULL, 'text', NULL, NULL, 1, 1, '♻️', '#44a08d', '2025-10-13 10:57:46', '2025-10-13 12:58:41', NULL),
(6, 'Le partage', 'Le partage', NULL, 'file', '/storage/thematique/xRD4tVxOpoGDQlcIQFvq1ycpiUwbLSp0GnfCSCvd.png', NULL, 1, 1, '🌍', '#f3ff99', '2025-10-13 11:44:48', '2025-10-13 12:53:21', NULL),
(7, 'Le recyclage', 'Le recyclage', 5, 'text', NULL, NULL, 8, 1, '🎨', '#3fab65', '2025-10-14 09:19:19', '2025-10-14 09:19:19', NULL);

INSERT INTO `types` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES
(1, 'Apprenti', NULL, '2025-10-11 18:24:50', '2025-10-11 18:24:50'),
(2, 'Parent', NULL, '2025-10-11 18:24:50', '2025-10-11 18:24:50'),
(3, 'Admin', NULL, '2025-10-11 18:25:31', '2025-10-11 18:25:31'),
(4, 'Super Admin', NULL, '2025-10-11 18:25:31', '2025-10-11 18:25:31');

INSERT INTO `users` (`id`, `code`, `id_google`, `name`, `email`, `type_id`, `sexe`, `age`, `telephone`, `profil`, `niveau_id`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'TEST12USER', NULL, 'Test User', 'moafogaus@gmail.com', 3, 'Masculin', 25, '678859210', '/storage/profil/profil.png', 1, NULL, '$2y$12$AElcNMo2rUuRYOdSxo.VreE15ZLJphBHTp0SBk5O.9DnzuelZBH3O', 'rng0cthO0Y', '2025-10-04 18:46:46', '2025-10-21 10:40:04', NULL),
(2, 'ADMIN01USER', NULL, 'Admin User', 'admin@example.com', 1, NULL, NULL, NULL, '/storage/profil/profil.png', NULL, '2025-10-04 18:46:46', '$2y$12$AElcNMo2rUuRYOdSxo.VreE15ZLJphBHTp0SBk5O.9DnzuelZBH3O', '21BzBAECib', '2025-10-04 18:46:46', '2025-10-04 18:46:46', NULL),
(3, 'ipED2D5B', NULL, 'Albert', 'albert@gmail.com', 1, 'Masculin', 13, '637635637', '/storage/profil/50FyUc327NpT2BLcjG5j7D9t9wfU03WyuJRTVWPa.png', 18, NULL, '$2y$12$EHYS3xp8QHTVUnVLm1GqZeBDqFs/A2ghApPj2EyCL8crYzGkyst5y', NULL, '2025-10-12 05:10:39', '2025-10-12 06:09:52', '2025-10-12 06:09:52'),
(4, 'BYVm3Vci', NULL, 'My admin', 'myadmin@gmail.com', 3, '1', 1, '1', '/storage/profil/Ub9tOyNx5571pG79GxJzBhIsAs6BxKVgu2wPQKLK.jpg', 2, NULL, '$2y$12$eWJ3BKfg4se6et26ahIR8eaZ6o20t1Kz9sReoxzWayrfizquWZhve', NULL, '2025-11-05 14:43:15', '2025-11-05 14:43:15', NULL);
